### ISSUE TITLE
Can't install role via  ansible-galaxy

### ISSUE THREAD

**Issue by andre487** [ElaoInfra/ansible-role-logrotate#1]
I got this error:

```
 $ ansible-galaxy install elao.logrotate
- downloading role 'logrotate', owned by elao
- downloading role from https://github.com/ElaoInfra/ansible-role-logrotate/archive/master.tar.gz
- error: failed to download the file.
- elao.logrotate was NOT installed successfully.
- you can use --ignore-errors to skip failed roles.
```

**Comment by nervo** [comment]
Yep, we have just updated all of our roles, and force versionning. So, from now, you have to specify the version, like that:

```
$ ansible-galaxy install elao.logrotate,1.0
```

Btw, we have also filled a ticket for ansible galaxy to take care of the default branch of a repo, and not systematically check master. See https://github.com/ansible/galaxy-issues/issues/87

**Comment by andre487** [comment]
I got it, thanks for the answer!
